# Generated by Django 4.1.2 on 2022-10-21 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToDo',
        ),
    ]
